
class WeatherReading:
    def __init__(self, data):
        self.pkt = data[0]
        self.max_temperature_c = data[1]
        self.mean_temperature_c = data[2]
        self.min_temperature_c = data[3]
        self.dew_point_c = data[4]
        self.mean_dew_point_c = data[5]
        self.min_dew_point_c = data[6]
        self.max_humidity = data[7]
        self.mean_humidity = data[8]
        self.min_humidity = data[9]
        self.max_sea_level_pressure_h_pa = data[10]
        self.mean_sea_level_pressure_h_pa = data[11]
        self.min_sea_level_pressure_h_pa = data[12]
        self.max_visibility_km = data[13]
        self.mean_visibility_km = data[14]
        self.minn_visibility_km = data[15]
        self.max_wind_speed_kmh = data[16]
        self.mean_wind_speed_kmh = data[17]
        self.max_gust_speed_kmh = data[18]
        self.precipitation_mm = data[19]
        self.cloud_cover = data[20]
        self.events = data[21]
        self.wind_dir_degrees = data[22]
